Sprint 1
don1andrew/middle.messenger.praktikum.yandex pull request #3
Opened 2023-05-13 08:40 UTC by don1andrew

2023-05-13 13:34 UTC, mikebars1995 requested changes
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

Работа проделана огромная


Что сделано отлично:

* Отличный дизайн чата
* `Readme` хорошо оформлен
* Проект задеплоен и отлично работает
* Отлично, что не забыли про `.gitignore`
* Отлично, что ограничиваете версию `node`
* Хорошая структура папок и файлов
* Отлично, что цвета вынесены в `css`-константы
* Отлично, что не забываете про `alt` в тегах `img`
* Отлично, что не забываете про тег `main` для главной части страницы
* Отлично, что установили язык страницы

Что нужно исправить:

* По заданию 1го спринта нужно давать инпутам **конкретные** атрибуты `name`, чтобы в 3м спринте не менять ничего при подключении к `Api`. Скрин из задания https://disk.yandex.ru/i/lSPqeGrAa20ayQ 
* На странице редактирования профиля не хватает инпута  `имя в чате`

Что можно улучшить:


* В проекте в некоторых файлах есть ошибка `EOF`. Для `git` важно наличие **пустой строки** в конце файла. Подробнее тут: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log Можно в настройки IDE добавить `insert_final_newline = true`
* Нужно ещё указать `viewport` для отзывчивости страницы



Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка `F12`) перед отправкой на ревью. 

Напоминаю, что работа может быть принята только после исправления всех критических замечаний `Нужно исправить`.

**Комментарии `Можно лучше` не обязательны к исправлению прямо сейчас, это рекомендации**

Удачного рефакторинга кода.

2023-05-13 13:34 UTC, mikebars1995 commented on src/error.js
> +})
**Можно лучше**

В проекте в некоторых файлах есть ошибка `EOF`. Для `git` важно наличие **пустой строки** в конце файла. Подробнее тут: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log Можно в настройки IDE добавить `insert_final_newline = true`

2023-05-13 13:34 UTC, mikebars1995 commented on src/pages/404.html
> +</head>
**Можно лучше**

Нужно ещё указать `viewport` для отзывчивости страницы
`<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">`
Так же есть еще ряд рекомендаций для `meta`, которые доступны [тут](https://github.com/thedaviddias/Front-End-Checklist#meta-tag)

2023-05-13 13:34 UTC, mikebars1995 commented on src/scripts/profile_edit.js
> +            name: 'name',
**Нужно исправить**


По заданию 1го спринта нужно давать инпутам **конкретные** атрибуты `name`, чтобы в 3м спринте не менять ничего при подключении к `Api`. Скрин из задания https://disk.yandex.ru/i/lSPqeGrAa20ayQ

2023-05-13 13:34 UTC, mikebars1995 commented on src/scripts/signup.js
> +            name: 'name',
**Нужно исправить**


По заданию 1го спринта нужно давать инпутам **конкретные** атрибуты `name`, чтобы в 3м спринте не менять ничего при подключении к `Api`. Скрин из задания https://disk.yandex.ru/i/lSPqeGrAa20ayQ

2023-05-13 13:34 UTC, mikebars1995 commented on src/scripts/profile_edit.js
> +    ]
**Нужно исправить**


На странице редактирования профиля не хватает инпута  `имя в чате`

2023-05-13 13:35 UTC, mikebars1995 reviewed
Здравствуйте. (**Нужно развернуть общий комментарий ↓**)

Работа проделана огромная


Что сделано отлично:

* Отличный дизайн чата
* `Readme` хорошо оформлен
* Проект задеплоен и отлично работает
* Отлично, что не забыли про `.gitignore`
* Отлично, что ограничиваете версию `node`
* Хорошая структура папок и файлов
* Отлично, что цвета вынесены в `css`-константы
* Отлично, что не забываете про `alt` в тегах `img`
* Отлично, что не забываете про тег `main` для главной части страницы
* Отлично, что установили язык страницы

Что нужно исправить:

* По заданию 1го спринта нужно давать инпутам **конкретные** атрибуты `name`, чтобы в 3м спринте не менять ничего при подключении к `Api`. Скрин из задания https://disk.yandex.ru/i/lSPqeGrAa20ayQ 
* На странице редактирования профиля не хватает инпута  `имя в чате`

Что можно улучшить:


* В проекте в некоторых файлах есть ошибка `EOF`. Для `git` важно наличие **пустой строки** в конце файла. Подробнее тут: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log Можно в настройки IDE добавить `insert_final_newline = true`
* Нужно ещё указать `viewport` для отзывчивости страницы



Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка `F12`) перед отправкой на ревью. 

Напоминаю, что работа может быть принята только после исправления всех критических замечаний `Нужно исправить`.

**Комментарии `Можно лучше` не обязательны к исправлению прямо сейчас, это рекомендации**

Удачного рефакторинга кода.

2023-05-18 14:22 UTC, don1andrew commented on src/error.js
> +})
Благодарю за замечания
А как увидеть, что такая ошибка присутствует в проекте?
Её показывает git diff, но только для файлов, которые отличаются этой самой строкой.

Для проверки, все ли файлы исправлены пока в голову пришло только такое:
```
#!/bin/bash

files=($(git ls-files))

for file in "${files[@]}"
do
  if [ "$(tail -c1 "$file")" != "" ]
  then
    echo "$file"
  fi
done
```

2023-05-18 14:26 UTC, don1andrew commented on src/scripts/profile_edit.js
> +            name: 'name',
Привел имена полей в соответствие с заданием
Требование назвать поле с фамилией как `second_name` немного непонятно, поэтому атрибут `name` установил как требуется, а отображаемое имя оставил корректным по смыслу.
Так же в задании не увидел какое значение нужно задать полю для контрольного ввода пароля, хотя в макете поля есть.

2023-05-18 14:32 UTC, don1andrew commented on src/scripts/profile_edit.js
> +    ]
Добавил нужный инпут.

Ещё подскажите пожалуйста по порядку взаимодействия здесь, на гитхабе - должен ли я прожимать `Resolve conversation` после того, как устранил конкретное замечание, или это делается ревьювером после подтверждения, что оно действительно устранено?

2023-05-18 14:33 UTC, don1andrew commented on src/pages/404.html
> +</head>
Добавил тэги `meta`

2023-05-18 23:43 UTC, mikebars1995 reviewed
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.

2023-05-18 23:43 UTC, mikebars1995 commented on src/scripts/profile_edit.js
> +    ]
Можете прожимать или не прожимать, выбор за вами)

Я это не прожимаю

2023-05-18 23:43 UTC, mikebars1995 commented on src/scripts/profile_edit.js
> +            name: 'name',
Для контрольного ввода пароля можно придумать `name` самостоятельно, так как он на сервер отправляться не будет

2023-05-31 21:42 UTC, merged